<!DOCTYPE html>
<html>

<head>
    <title>Laporan Inventory Items</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 11px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header h2 {
            margin: 0;
            color: #1e293b;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table,
        th,
        td {
            border: 1px solid black;
        }

        th {
            background-color: #2E2EFE;
            color: white;
            padding: 10px 5px;
            text-transform: uppercase;
        }

        /* Padding td diperkecil sedikit biar lebih clean */
        td {
            padding: 6px 8px;
            text-align: left;
            vertical-align: middle;
            color: #334155;
        }

        .text-center {
            text-align: center;
        }

        /* Nama barang pake font normal saja */
        .item-name {
            font-weight: normal;
            text-transform: capitalize;
        }

        .footer {
            margin-top: 20px;
            font-size: 9px;
            text-align: right;
            color: #64748b;
        }
    </style>
</head>

<body>
    <div class="header">
        <h2>LAPORAN DATA MANAGEMENT ITEMS</h2>
        <p>Dicetak pada: {{ \Carbon\Carbon::now()->timezone('Asia/Jakarta')->format('d/m/Y H:i') }} WIB</p>
    </div>

    <table>
        <thead>
            <tr>
                <th width="30px">NO</th>
                <th width="120px">KATEGORI</th>
                <th>NAMA BARANG</th>
                <th width="90px">TOTAL STOK</th>
                <th width="110px">TOTAL DIPINJAM</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $index => $product)
                <tr>
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td class="text-center">{{ $product->category->name ?? 'General' }}</td>
                    <td class="item-name">{{ $product->name }}</td>
                    <td class="text-center">{{ $product->total_stock ?? 0 }} Unit</td>
                    <td class="text-center">{{ $product->total_pinjam ?? 0 }} Unit</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by {{ auth()->user()->name }} - Inventory System Management
    </div>
</body>

</html>